### ISSUE TITLE
[Question] Terrain Manipulation

### ISSUE THREAD

**Issue by Skittlekirby** [Terraformer9x/RebalancedMineshaft#2]
Hey,

Super nice mod to see, I think these are really effective changes.

I was wondering if you might update this mod to also adjust the terrain in the caves themselves? In my experience it has been easy to get stuck on geometry, especially in the parts in which you're supposed to go underwater.  It's really frustrating and ruins the immersion; I'm alright with claustrophobia but even enemies will get stuck on things. Sometimes you're forced to go underwater to progress through the cave, and if you find something like a cash register the weight alone can make it practically impossible to bring back through the water. 

I understand that's probably a vastly different thing to change, though. As is I think this mod is super underrated and I love the nuanced, minor changes your other mods add/change. you have really good instinct for what makes sense to change but keeping it feeling vanilla and i gotta use the moment to say thanks overall :)

**Comment by Terraformer9x** [comment]
Changing the collision mesh of the caves shouldn't be too hard, the only one that's really problematic is the water cave tile and I've even been contemplating making whether there's water present RNG.

Thank you for the compliment, I'm glad you really like my mods despite them being niche! ^^

**Comment by MiraakThuri** [comment]
It's a good idea to rework those collisions i think
also really like the mod, never liked the fact that the mineshaft was balanced so differently compared to the other interiors, mostly the scrap count

**Comment by Terraformer9x** [comment]
I improved upon the water tunnel's collision geometry with https://github.com/Terraformer9x/RebalancedMineshaft/commit/438ce6166ba782408c8de460711a0bd30e174fe2. I'm still gonna leave this open for a bit just in case.
